[package]
name = "qf-helper"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[lib]
name = "qf_helper"
path = "src/lib.rs"

[[bin]]
name = "qf-helper"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.12.19", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread", "time", "signal"] }
toml = "0.8"
chrono = "0.4"
qf_log_parser = { path = "../qf_log_parser" }

[dev-dependencies]
axum = "0.8"
tempfile = "3"
tokio = { version = "1.45.1", features = ["full"] }
